-- MySQL Script generated by MySQL Workbench
-- Thu Dec 10 00:42:20 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema educacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema educacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `educacao` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `educacao` ;

-- -----------------------------------------------------
-- Table `educacao`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Professor` (
  `idProfessor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `DataNasc` DATE NOT NULL,
  `DataContratação` DATE NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Instituto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Instituto` (
  `idInstituto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idInstituto`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Departamento` (
  `idDepartamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Instituto_idInstituto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  INDEX `fk_Departamento_Instituto_idx` (`Instituto_idInstituto` ASC),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC),
  CONSTRAINT `fk_Departamento_Instituto`
    FOREIGN KEY (`Instituto_idInstituto`)
    REFERENCES `educacao`.`Instituto` (`idInstituto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Curso` (
  `idCurso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Duracao` INT NOT NULL,
  `CreditosForm` INT NOT NULL,
  `Departamento_idDepartamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_Curso_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC),
  CONSTRAINT `fk_Curso_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `educacao`.`Departamento` (`idDepartamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Projeto` (
  `idProjeto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(300) NOT NULL,
  `Área de Pesquisa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Aluno` (
  `idAluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `DataNasc` DATE NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `DataIngresso` DATE NOT NULL,
  `RG` VARCHAR(45) NOT NULL,
  `Matricula` VARCHAR(45) NOT NULL,
  `Curso_idCursos` INT UNSIGNED NOT NULL,
  `Foto` LONGBLOB NULL,
  `Projeto_idProjeto` INT UNSIGNED NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fk_Aluno_Curso1_idx` (`Curso_idCursos` ASC),
  INDEX `fk_Aluno_Projeto1_idx` (`Projeto_idProjeto` ASC),
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCursos`)
    REFERENCES `educacao`.`Curso` (`idCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Aluno_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `educacao`.`Projeto` (`idProjeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Disciplina` (
  `idDisciplinas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Código` INT NOT NULL,
  `Créditos` INT NOT NULL,
  `Departamento_idDepartamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDisciplinas`),
  INDEX `fk_Disciplina_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  CONSTRAINT `fk_Disciplina_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `educacao`.`Departamento` (`idDepartamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Sala` (
  `idSalas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSalas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`PreRequisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`PreRequisito` (
  `idPre-requisito` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Disciplinas_idDisciplinas` INT UNSIGNED NULL,
  `Disciplinas_idDisciplinas1` INT UNSIGNED NULL,
  PRIMARY KEY (`idPre-requisito`),
  INDEX `fk_Disciplinas_has_Disciplinas_Disciplinas2_idx` (`Disciplinas_idDisciplinas1` ASC),
  INDEX `fk_Disciplinas_has_Disciplinas_Disciplinas1_idx` (`Disciplinas_idDisciplinas` ASC),
  CONSTRAINT `fk_Disciplinas_has_Disciplinas_Disciplinas1`
    FOREIGN KEY (`Disciplinas_idDisciplinas`)
    REFERENCES `educacao`.`Disciplina` (`idDisciplinas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Disciplinas_has_Disciplinas_Disciplinas2`
    FOREIGN KEY (`Disciplinas_idDisciplinas1`)
    REFERENCES `educacao`.`Disciplina` (`idDisciplinas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Turma` (
  `idTurma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Letra` CHAR(1) NOT NULL,
  `Disciplina_idDisciplinas` INT UNSIGNED NOT NULL,
  `Professor_idProfessor` INT UNSIGNED NULL,
  `Sala_idSalas` INT UNSIGNED NULL,
  `Horário` TIME(6) NULL,
  PRIMARY KEY (`idTurma`, `Disciplina_idDisciplinas`),
  INDEX `fk_Turma_Disciplina1_idx` (`Disciplina_idDisciplinas` ASC),
  INDEX `fk_Turma_Professor1_idx` (`Professor_idProfessor` ASC),
  INDEX `fk_Turma_Sala1_idx` (`Sala_idSalas` ASC),
  CONSTRAINT `fk_Turma_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplinas`)
    REFERENCES `educacao`.`Disciplina` (`idDisciplinas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Turma_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `educacao`.`Professor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Turma_Sala1`
    FOREIGN KEY (`Sala_idSalas`)
    REFERENCES `educacao`.`Sala` (`idSalas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Matricula` (
  `Aluno_idAluno` INT UNSIGNED NOT NULL,
  `Turma_idTurma` INT UNSIGNED NOT NULL,
  `Turma_Disciplina_idDisciplinas` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Turma_Disciplina_idDisciplinas`, `Aluno_idAluno`),
  INDEX `fk_Aluno_has_Turma_Turma1_idx` (`Turma_idTurma` ASC, `Turma_Disciplina_idDisciplinas` ASC),
  INDEX `fk_Aluno_has_Turma_Aluno1_idx` (`Aluno_idAluno` ASC),
  CONSTRAINT `fk_Aluno_has_Turma_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `educacao`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Aluno_has_Turma_Turma1`
    FOREIGN KEY (`Turma_idTurma` , `Turma_Disciplina_idDisciplinas`)
    REFERENCES `educacao`.`Turma` (`idTurma` , `Disciplina_idDisciplinas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Laboratorio` (
  `idLaboratorio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Sala_idSalas` INT UNSIGNED NOT NULL,
  `Departamento_idDepartamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLaboratorio`),
  INDEX `fk_Laboratorio_Sala1_idx` (`Sala_idSalas` ASC),
  INDEX `fk_Laboratorio_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC),
  CONSTRAINT `fk_Laboratorio_Sala1`
    FOREIGN KEY (`Sala_idSalas`)
    REFERENCES `educacao`.`Sala` (`idSalas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Laboratorio_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `educacao`.`Departamento` (`idDepartamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Tipo_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Tipo_Item` (
  `idTipo_Item` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idTipo_Item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Item` (
  `idItem` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Quantidade` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Tipo_Item_idTipo_Item` INT UNSIGNED NOT NULL,
  `Laboratorio_idLaboratório` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_Item_Tipo_Item1_idx` (`Tipo_Item_idTipo_Item` ASC),
  INDEX `fk_Item_Laboratorio1_idx` (`Laboratorio_idLaboratório` ASC),
  CONSTRAINT `fk_Item_Tipo_Item1`
    FOREIGN KEY (`Tipo_Item_idTipo_Item`)
    REFERENCES `educacao`.`Tipo_Item` (`idTipo_Item`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Item_Laboratorio1`
    FOREIGN KEY (`Laboratorio_idLaboratório`)
    REFERENCES `educacao`.`Laboratorio` (`idLaboratorio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educacao`.`Projeto_Prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`Projeto_Prof` (
  `idProjeto_Prof` INT NOT NULL AUTO_INCREMENT,
  `Projeto_idProjeto` INT UNSIGNED NOT NULL,
  `Professor_idProfessor` INT UNSIGNED NOT NULL,
  INDEX `fk_Projeto_has_Professor_Professor1_idx` (`Professor_idProfessor` ASC),
  INDEX `fk_Projeto_has_Professor_Projeto1_idx` (`Projeto_idProjeto` ASC),
  PRIMARY KEY (`idProjeto_Prof`),
  CONSTRAINT `fk_Projeto_has_Professor_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `educacao`.`Projeto` (`idProjeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Projeto_has_Professor_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `educacao`.`Professor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `educacao` ;

-- -----------------------------------------------------
-- Placeholder table for view `educacao`.`CursoView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educacao`.`CursoView` (`idCurso` INT, `Nome` INT, `Duracao` INT);

-- -----------------------------------------------------
-- View `educacao`.`CursoView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacao`.`CursoView`;
USE `educacao`;
CREATE  OR REPLACE VIEW `CursoView` AS
SELECT idCurso, Nome, Duracao FROM Curso
WHERE Duracao = 8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
